{
  "ref": "0adae405504f2bf7d4c62d4880704f37fb6ee37c",
  "nextjsVersion": "Next.js v13.1.7-canary.7",
  "result": [
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (16, 1)",
      "name": "test/development/acceptance-app/component-stack.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 2,
        "numPendingTestSuites": 0,
        "numPendingTests": 4,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 8,
        "openHandles": [],
        "snapshot": {
          "added": 2,
          "didUpdate": false,
          "failure": true,
          "filesAdded": 1,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 1,
          "filesUpdated": 0,
          "matched": 0,
          "total": 4,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 2,
          "updated": 0
        },
        "startTime": 1675848402858,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "ReactRefreshLogBox default"
                ],
                "failureMessages": [],
                "fullName": "ReactRefreshLogBox default empty _app shows logbox",
                "location": null,
                "status": "pending",
                "title": "empty _app shows logbox"
              },
              {
                "ancestorTitles": [
                  "ReactRefreshLogBox default"
                ],
                "failureMessages": [],
                "fullName": "ReactRefreshLogBox default empty _document shows logbox",
                "location": null,
                "status": "pending",
                "title": "empty _document shows logbox"
              },
              {
                "ancestorTitles": [
                  "ReactRefreshLogBox default"
                ],
                "failureMessages": [],
                "fullName": "ReactRefreshLogBox default _app syntax error shows logbox",
                "location": null,
                "status": "pending",
                "title": "_app syntax error shows logbox"
              },
              {
                "ancestorTitles": [
                  "ReactRefreshLogBox default"
                ],
                "failureMessages": [],
                "fullName": "ReactRefreshLogBox default _document syntax error shows logbox",
                "location": null,
                "status": "pending",
                "title": "_document syntax error shows logbox"
              },
              {
                "ancestorTitles": [
                  "ReactRefreshLogBox turbo"
                ],
                "failureMessages": [
                  "Error: expect(received).toMatchInlineSnapshot(snapshot)\n\nSnapshot name: `ReactRefreshLogBox turbo empty _app shows logbox 1`\n\nSnapshot: \"Error: The default export is not a React Component in page: \\\"/_app\\\"\"\nReceived: \"Error during SSR Rendering\"\n    at Object.<anonymous> (/work/test/development/acceptance/ReactRefreshLogBox-app-doc.test.ts:31:52)"
                ],
                "fullName": "ReactRefreshLogBox turbo empty _app shows logbox",
                "location": null,
                "status": "failed",
                "title": "empty _app shows logbox"
              },
              {
                "ancestorTitles": [
                  "ReactRefreshLogBox turbo"
                ],
                "failureMessages": [
                  "Error: expect(received).toMatchInlineSnapshot(snapshot)\n\nSnapshot name: `ReactRefreshLogBox turbo empty _document shows logbox 1`\n\nSnapshot: \"Error: The default export is not a React Component in page: \\\"/_document\\\"\"\nReceived: \"Error during SSR Rendering\"\n    at Object.<anonymous> (/work/test/development/acceptance/ReactRefreshLogBox-app-doc.test.ts:61:52)"
                ],
                "fullName": "ReactRefreshLogBox turbo empty _document shows logbox",
                "location": null,
                "status": "failed",
                "title": "empty _document shows logbox"
              },
              {
                "ancestorTitles": [
                  "ReactRefreshLogBox turbo"
                ],
                "failureMessages": [],
                "fullName": "ReactRefreshLogBox turbo _app syntax error shows logbox",
                "location": null,
                "status": "passed",
                "title": "_app syntax error shows logbox"
              },
              {
                "ancestorTitles": [
                  "ReactRefreshLogBox turbo"
                ],
                "failureMessages": [],
                "fullName": "ReactRefreshLogBox turbo _document syntax error shows logbox",
                "location": null,
                "status": "passed",
                "title": "_document syntax error shows logbox"
              }
            ],
            "endTime": 1675848516374,
            "message": "  ● ReactRefreshLogBox turbo › empty _app shows logbox\n\n    expect(received).toMatchInlineSnapshot(snapshot)\n\n    Snapshot name: `ReactRefreshLogBox turbo empty _app shows logbox 1`\n\n    Snapshot: \"Error: The default export is not a React Component in page: \\\"/_app\\\"\"\n    Received: \"Error during SSR Rendering\"\n\n      29 |       )\n      30 |       expect(await session.hasRedbox(true)).toBe(true)\n    > 31 |       expect(await session.getRedboxDescription()).toMatchInlineSnapshot(\n         |                                                    ^\n      32 |         `\"Error: The default export is not a React Component in page: \\\\\"/_app\\\\\"\"`\n      33 |       )\n      34 |\n\n      at Object.<anonymous> (development/acceptance/ReactRefreshLogBox-app-doc.test.ts:31:52)\n\n  ● ReactRefreshLogBox turbo › empty _document shows logbox\n\n    expect(received).toMatchInlineSnapshot(snapshot)\n\n    Snapshot name: `ReactRefreshLogBox turbo empty _document shows logbox 1`\n\n    Snapshot: \"Error: The default export is not a React Component in page: \\\"/_document\\\"\"\n    Received: \"Error during SSR Rendering\"\n\n      59 |       )\n      60 |       expect(await session.hasRedbox(true)).toBe(true)\n    > 61 |       expect(await session.getRedboxDescription()).toMatchInlineSnapshot(\n         |                                                    ^\n      62 |         `\"Error: The default export is not a React Component in page: \\\\\"/_document\\\\\"\"`\n      63 |       )\n      64 |\n\n      at Object.<anonymous> (development/acceptance/ReactRefreshLogBox-app-doc.test.ts:61:52)\n",
            "name": "/work/test/development/acceptance/ReactRefreshLogBox-app-doc.test.ts",
            "startTime": 1675848402948,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (16, 1)",
      "name": "test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 2,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675848613209,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "fetch failures have good stack traces in edge runtime"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"src/fetcher.js\"\nReceived string:    \"yarn run v1.22.19\n$ /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/node_modules/.bin/next --turbo\n>>> TURBOPACK (alpha)·\nThank you for trying Next.js v13 with Turbopack! As a reminder,\nTurbopack is currently in alpha and not yet ready for production.\nWe appreciate your ongoing support as we work to make it ready\nfor everyone.·\nLearn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\nPlease direct feedback to: https://nextjs.link/turbopack-feedback·\ninfo  - Using locally built binary of @next/swc\nLoading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0 --is-next-dev-command --root /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0 --no-open]\n\u001b[32mready\u001b[39m - started server on 0.0.0.0:41841, url: http://localhost:41841\n\u001b[35mevent\u001b[39m - initial compilation 4.928ms\n[500] /api/unknown-domain (1166ms)\n\"\n    at Object.<anonymous> (/work/test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:25:32)"
                ],
                "fullName": "fetch failures have good stack traces in edge runtime when awaiting `fetch` using an unknown domain, stack traces are preserved",
                "location": null,
                "status": "failed",
                "title": "when awaiting `fetch` using an unknown domain, stack traces are preserved"
              },
              {
                "ancestorTitles": [
                  "fetch failures have good stack traces in edge runtime"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /at.+\\/pages\\/api\\/unknown-domain-no-await.js/\n\nyarn run v1.22.19\n$ /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/node_modules/.bin/next --turbo\n>>> TURBOPACK (alpha)\n\nThank you for trying Next.js v13 with Turbopack! As a reminder,\nTurbopack is currently in alpha and not yet ready for production.\nWe appreciate your ongoing support as we work to make it ready\nfor everyone.\n\nLearn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\nPlease direct feedback to: https://nextjs.link/turbopack-feedback\n\ninfo  - Using locally built binary of @next/swc\nLoading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0 --is-next-dev-command --root /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0 --no-open]\nready - started server on 0.0.0.0:41841, url: http://localhost:41841\nevent - initial compilation 4.928ms\n[500] /api/unknown-domain (1166ms)\nevent - updated in 1166ms\nstack is: Error: fetch failed\n    at context.fetch (/tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/node_modules/.pnpm/file+..+next-repo-b5ad786f33c548084b8286b610f3c086_zwwtlgwwytetg6qkhm5oqiwese/node_modules/next/dist/server/web/sandbox/context.js:167:38)\n    at Object.UnknownDomainEndpoint [as handler] (/tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js:13:5)\n    at Object.adapter (/tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/edge/chunks/d2b48_next_dist_server_web_adapter.js:98:33)\n    at default (/tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js_next-edge-bootstrap_1071bf.ts._.js:18:278)\n    at /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/node_modules/.pnpm/file+..+next-repo-b5ad786f33c548084b8286b610f3c086_zwwtlgwwytetg6qkhm5oqiwese/node_modules/next/dist/server/web/sandbox/sandbox.js:73:30\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async runEdgeFunction (/tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:114:20)\n    at async /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:84:5\n    at async endOperation (/tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:109:13)\n    at async Promise.all (index 0)\n    at async /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:58:13\nevent - updated in 273ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:40:7)"
                ],
                "fullName": "fetch failures have good stack traces in edge runtime when returning `fetch` using an unknown domain, stack traces are preserved",
                "location": null,
                "status": "failed",
                "title": "when returning `fetch` using an unknown domain, stack traces are preserved"
              }
            ],
            "endTime": 1675848663765,
            "message": "  ● fetch failures have good stack traces in edge runtime › when awaiting `fetch` using an unknown domain, stack traces are preserved\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"src/fetcher.js\"\n    Received string:    \"yarn run v1.22.19\n    $ /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/node_modules/.bin/next --turbo\n    >>> TURBOPACK (alpha)·\n    Thank you for trying Next.js v13 with Turbopack! As a reminder,\n    Turbopack is currently in alpha and not yet ready for production.\n    We appreciate your ongoing support as we work to make it ready\n    for everyone.·\n    Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\n    Please direct feedback to: https://nextjs.link/turbopack-feedback·\n    info  - Using locally built binary of @next/swc\n    Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0 --is-next-dev-command --root /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0 --no-open]\n    \u001b[32mready\u001b[39m - started server on 0.0.0.0:41841, url: http://localhost:41841\n    \u001b[35mevent\u001b[39m - initial compilation 4.928ms\n    [500] /api/unknown-domain (1166ms)\n    \"\n\n      23 |         expect(next.cliOutput).toMatch(/at.+\\/pages\\/api\\/unknown-domain.js/)\n      24 |       } else if (isNextDev) {\n    > 25 |         expect(next.cliOutput).toContain('src/fetcher.js')\n         |                                ^\n      26 |\n      27 |         expect(await hasRedbox(browser, true)).toBe(true)\n      28 |         const source = await getRedboxSource(browser)\n\n      at Object.<anonymous> (e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:25:32)\n\n  ● fetch failures have good stack traces in edge runtime › when returning `fetch` using an unknown domain, stack traces are preserved\n\n    TIMED OUT: /at.+\\/pages\\/api\\/unknown-domain-no-await.js/\n\n    yarn run v1.22.19\n    $ /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/node_modules/.bin/next --turbo\n    >>> TURBOPACK (alpha)\n\n    Thank you for trying Next.js v13 with Turbopack! As a reminder,\n    Turbopack is currently in alpha and not yet ready for production.\n    We appreciate your ongoing support as we work to make it ready\n    for everyone.\n\n    Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\n    Please direct feedback to: https://nextjs.link/turbopack-feedback\n\n    info  - Using locally built binary of @next/swc\n    Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0 --is-next-dev-command --root /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0 --no-open]\n    ready - started server on 0.0.0.0:41841, url: http://localhost:41841\n    event - initial compilation 4.928ms\n    [500] /api/unknown-domain (1166ms)\n    event - updated in 1166ms\n    stack is: Error: fetch failed\n\n      at context.fetch (../../tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/node_modules/.pnpm/file+..+next-repo-b5ad786f33c548084b8286b610f3c086_zwwtlgwwytetg6qkhm5oqiwese/node_modules/next/dist/server/web/sandbox/context.js:167:38)\n      at Object.UnknownDomainEndpoint [as handler] (../../tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js:13:5)\n      at Object.adapter (../../tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/edge/chunks/d2b48_next_dist_server_web_adapter.js:98:33)\n      at default (../../tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js_next-edge-bootstrap_1071bf.ts._.js:18:278)\n      at ../../tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/node_modules/.pnpm/file+..+next-repo-b5ad786f33c548084b8286b610f3c086_zwwtlgwwytetg6qkhm5oqiwese/node_modules/next/dist/server/web/sandbox/sandbox.js:73:30\n      at async runEdgeFunction (../../tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:114:20)\n      at ../async /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:84:5\n      at async endOperation (../../tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:109:13)\n          at async Promise.all (index 0)\n      at ../async /tmp/next-install-e7b95c8ca1d4ecc1b5c622731b55b4286800351d52f8b8b7369e4cd28af75ae0/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:58:13\n      event - updated in 273ms\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:40:7)\n",
            "name": "/work/test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts",
            "startTime": 1675848613306,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (16, 1)",
      "name": "test/integration/edge-runtime-response-error/test/index.test.js",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 2,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 4,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675848757039,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"Expected an instance of Response to be returned\"\nReceived string:    \"Loading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 45637 --root /work --no-open]\n\"\n    at Object.<anonymous> (/work/test/integration/edge-runtime-response-error/test/index.test.js:70:35)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
                ],
                "fullName": "Edge runtime code with imports test error if response is not Response type Edge API dev test Response",
                "location": null,
                "status": "failed",
                "title": "Edge API dev test Response"
              },
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [],
                "fullName": "Edge runtime code with imports test error if response is not Response type Edge API build test Response",
                "location": null,
                "status": "passed",
                "title": "Edge API build test Response"
              },
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"Expected an instance of Response to be returned\"\nReceived string:    \"Loading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 45923 --root /work --no-open]\n\"\n    at Object.<anonymous> (/work/test/integration/edge-runtime-response-error/test/index.test.js:70:35)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
                ],
                "fullName": "Edge runtime code with imports test error if response is not Response type Middleware dev test Response",
                "location": null,
                "status": "failed",
                "title": "Middleware dev test Response"
              },
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [],
                "fullName": "Edge runtime code with imports test error if response is not Response type Middleware build test Response",
                "location": null,
                "status": "passed",
                "title": "Middleware build test Response"
              }
            ],
            "endTime": 1675848801273,
            "message": "  ● Edge runtime code with imports › test error if response is not Response type › Edge API dev test Response\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"Expected an instance of Response to be returned\"\n    Received string:    \"Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 45637 --root /work --no-open]\n    \"\n\n      68 |       context.app = await launchApp(context.appDir, context.appPort, appOption)\n      69 |       const res = await fetchViaHTTP(context.appPort, url)\n    > 70 |       expect(context.logs.stderr).toContain(\n         |                                   ^\n      71 |         'Expected an instance of Response to be returned'\n      72 |       )\n      73 |       expect(res.status).toBe(500)\n\n      at Object.<anonymous> (integration/edge-runtime-response-error/test/index.test.js:70:35)\n\n  ● Edge runtime code with imports › test error if response is not Response type › Middleware dev test Response\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"Expected an instance of Response to be returned\"\n    Received string:    \"Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 45923 --root /work --no-open]\n    \"\n\n      68 |       context.app = await launchApp(context.appDir, context.appPort, appOption)\n      69 |       const res = await fetchViaHTTP(context.appPort, url)\n    > 70 |       expect(context.logs.stderr).toContain(\n         |                                   ^\n      71 |         'Expected an instance of Response to be returned'\n      72 |       )\n      73 |       expect(res.status).toBe(500)\n\n      at Object.<anonymous> (integration/edge-runtime-response-error/test/index.test.js:70:35)\n",
            "name": "/work/test/integration/edge-runtime-response-error/test/index.test.js",
            "startTime": 1675848757147,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (16, 2)",
      "name": "test/development/acceptance-app/editor-links.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 3,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 3,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675848609241,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "api-route-errors cli output"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /pages\\/api/\n\n[500] /api/error (927ms)\n\u001b[2K\u001b[35mevent\u001b[39m - updated in 927ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/development/api-route-errors/index.test.ts:23:5)"
                ],
                "fullName": "api-route-errors cli output error",
                "location": null,
                "status": "failed",
                "title": "error"
              },
              {
                "ancestorTitles": [
                  "api-route-errors cli output"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /pages\\/api/\n\n[500] /api/uncaught-exception (116ms)\n\u001b[2K\u001b[35mevent\u001b[39m - updated in 116ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/development/api-route-errors/index.test.ts:37:5)"
                ],
                "fullName": "api-route-errors cli output uncaught exception",
                "location": null,
                "status": "failed",
                "title": "uncaught exception"
              },
              {
                "ancestorTitles": [
                  "api-route-errors cli output"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /pages\\/api/\n\n[500] /api/unhandled-rejection (144ms)\n\u001b[2K\u001b[35mevent\u001b[39m - updated in 144ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/development/api-route-errors/index.test.ts:55:5)"
                ],
                "fullName": "api-route-errors cli output unhandled rejection",
                "location": null,
                "status": "failed",
                "title": "unhandled rejection"
              }
            ],
            "endTime": 1675848720014,
            "message": "  ● api-route-errors cli output › error\n\n    TIMED OUT: /pages\\/api/\n\n    [500] /api/error (927ms)\n    \u001b[2K\u001b[35mevent\u001b[39m - updated in 927ms\n\n      559 |\n      560 |   if (hardError) {\n    > 561 |     throw new Error('TIMED OUT: ' + regex + '\\n\\n' + content)\n          |           ^\n      562 |   }\n      563 |   return false\n      564 | }\n\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (development/api-route-errors/index.test.ts:23:5)\n\n  ● api-route-errors cli output › uncaught exception\n\n    TIMED OUT: /pages\\/api/\n\n    [500] /api/uncaught-exception (116ms)\n    \u001b[2K\u001b[35mevent\u001b[39m - updated in 116ms\n\n      559 |\n      560 |   if (hardError) {\n    > 561 |     throw new Error('TIMED OUT: ' + regex + '\\n\\n' + content)\n          |           ^\n      562 |   }\n      563 |   return false\n      564 | }\n\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (development/api-route-errors/index.test.ts:37:5)\n\n  ● api-route-errors cli output › unhandled rejection\n\n    TIMED OUT: /pages\\/api/\n\n    [500] /api/unhandled-rejection (144ms)\n    \u001b[2K\u001b[35mevent\u001b[39m - updated in 144ms\n\n      559 |\n      560 |   if (hardError) {\n    > 561 |     throw new Error('TIMED OUT: ' + regex + '\\n\\n' + content)\n          |           ^\n      562 |   }\n      563 |   return false\n      564 | }\n\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (development/api-route-errors/index.test.ts:55:5)\n",
            "name": "/work/test/development/api-route-errors/index.test.ts",
            "startTime": 1675848609331,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (16, 2)",
      "name": "test/e2e/app-dir/app-rendering/rendering.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 2,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675848829945,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "app-dir alias handling"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"click</button>\"\nReceived string:    \"Execution of get_from_source failed·\nCaused by:\n    0: Execution of resolve_source_request failed\n    1: Execution of CombinedContentSource::get failed\n    2: Execution of create_app_source failed\n    3: Execution of load_next_config failed\n    4: Execution of evaluate failed\n    5: node process exited before we could connect to it with exit status: 1\"\n    at Object.<anonymous> (/work/test/e2e/app-dir/app-alias/app-alias.test.ts:16:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
                ],
                "fullName": "app-dir alias handling should handle typescript paths alias correctly",
                "location": null,
                "status": "failed",
                "title": "should handle typescript paths alias correctly"
              },
              {
                "ancestorTitles": [
                  "app-dir alias handling"
                ],
                "failureMessages": [
                  "page.waitForSelector: Timeout 30000ms exceeded.\n=========================== logs ===========================\nwaiting for locator('button')\n============================================================\n    at /work/test/lib/browsers/playwright.ts:331:10"
                ],
                "fullName": "app-dir alias handling should resolve css imports from outside with src folder presented",
                "location": null,
                "status": "failed",
                "title": "should resolve css imports from outside with src folder presented"
              }
            ],
            "endTime": 1675848882644,
            "message": "  ● app-dir alias handling › should handle typescript paths alias correctly\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"click</button>\"\n    Received string:    \"Execution of get_from_source failed·\n    Caused by:\n        0: Execution of resolve_source_request failed\n        1: Execution of CombinedContentSource::get failed\n        2: Execution of create_app_source failed\n        3: Execution of load_next_config failed\n        4: Execution of evaluate failed\n        5: node process exited before we could connect to it with exit status: 1\"\n\n      14 |     it('should handle typescript paths alias correctly', async () => {\n      15 |       const html = await next.render('/button')\n    > 16 |       expect(html).toContain('click</button>')\n         |                    ^\n      17 |     })\n      18 |\n      19 |     it('should resolve css imports from outside with src folder presented', async () => {\n\n      at Object.<anonymous> (e2e/app-dir/app-alias/app-alias.test.ts:16:20)\n\n  ● app-dir alias handling › should resolve css imports from outside with src folder presented\n\n    page.waitForSelector: Timeout 30000ms exceeded.\n    =========================== logs ===========================\n    waiting for locator('button')\n    ============================================================\n\n      329 |     return this.chain(() => {\n      330 |       return page\n    > 331 |         .waitForSelector(selector, { timeout, state: 'attached' })\n          |          ^\n      332 |         .then(async (el) => {\n      333 |           // it seems selenium waits longer and tests rely on this behavior\n      334 |           // so we wait for the load event fire before returning\n\n      at lib/browsers/playwright.ts:331:10\n",
            "name": "/work/test/e2e/app-dir/app-alias/app-alias.test.ts",
            "startTime": 1675848830036,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (18, 1)",
      "name": "test/development/acceptance-app/component-stack.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 1,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 1,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675848536582,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "Component Stack in error overlay"
                ],
                "failureMessages": [
                  "page.waitForSelector: Timeout 30000ms exceeded.\n=========================== logs ===========================\nwaiting for locator('[data-nextjs-toast]')\n============================================================\n    at /work/test/lib/browsers/playwright.ts:331:10"
                ],
                "fullName": "Component Stack in error overlay should show a component stack on hydration error",
                "location": null,
                "status": "failed",
                "title": "should show a component stack on hydration error"
              }
            ],
            "endTime": 1675848600081,
            "message": "  ● Component Stack in error overlay › should show a component stack on hydration error\n\n    page.waitForSelector: Timeout 30000ms exceeded.\n    =========================== logs ===========================\n    waiting for locator('[data-nextjs-toast]')\n    ============================================================\n\n      329 |     return this.chain(() => {\n      330 |       return page\n    > 331 |         .waitForSelector(selector, { timeout, state: 'attached' })\n          |          ^\n      332 |         .then(async (el) => {\n      333 |           // it seems selenium waits longer and tests rely on this behavior\n      334 |           // so we wait for the load event fire before returning\n\n      at lib/browsers/playwright.ts:331:10\n",
            "name": "/work/test/development/acceptance-app/component-stack.test.ts",
            "startTime": 1675848536675,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (18, 1)",
      "name": "test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 2,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675848678085,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "fetch failures have good stack traces in edge runtime"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"src/fetcher.js\"\nReceived string:    \"yarn run v1.22.19\n$ /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/node_modules/.bin/next --turbo\n>>> TURBOPACK (alpha)·\nThank you for trying Next.js v13 with Turbopack! As a reminder,\nTurbopack is currently in alpha and not yet ready for production.\nWe appreciate your ongoing support as we work to make it ready\nfor everyone.·\nLearn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\nPlease direct feedback to: https://nextjs.link/turbopack-feedback·\ninfo  - Using locally built binary of @next/swc\nLoading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191 --is-next-dev-command --root /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191 --no-open]\n\u001b[32mready\u001b[39m - started server on 0.0.0.0:32881, url: http://localhost:32881\n\u001b[35mevent\u001b[39m - initial compilation 6.044ms\n[500] /api/unknown-domain (1122ms)\n\"\n    at Object.<anonymous> (/work/test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:25:32)"
                ],
                "fullName": "fetch failures have good stack traces in edge runtime when awaiting `fetch` using an unknown domain, stack traces are preserved",
                "location": null,
                "status": "failed",
                "title": "when awaiting `fetch` using an unknown domain, stack traces are preserved"
              },
              {
                "ancestorTitles": [
                  "fetch failures have good stack traces in edge runtime"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /at.+\\/pages\\/api\\/unknown-domain-no-await.js/\n\nyarn run v1.22.19\n$ /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/node_modules/.bin/next --turbo\n>>> TURBOPACK (alpha)\n\nThank you for trying Next.js v13 with Turbopack! As a reminder,\nTurbopack is currently in alpha and not yet ready for production.\nWe appreciate your ongoing support as we work to make it ready\nfor everyone.\n\nLearn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\nPlease direct feedback to: https://nextjs.link/turbopack-feedback\n\ninfo  - Using locally built binary of @next/swc\nLoading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191 --is-next-dev-command --root /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191 --no-open]\nready - started server on 0.0.0.0:32881, url: http://localhost:32881\nevent - initial compilation 6.044ms\n[500] /api/unknown-domain (1122ms)\nevent - updated in 1122ms\nstack is: Error: fetch failed\n    at context.fetch (/tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/node_modules/.pnpm/file+..+next-repo-cc68aa895ffa81a871739457a575a08d_s35yvm4iil2ppnxycg6o257o2y/node_modules/next/dist/server/web/sandbox/context.js:167:38)\n    at Object.UnknownDomainEndpoint [as handler] (/tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js:13:5)\n    at Object.adapter (/tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/edge/chunks/b5a0f_next_dist_server_web_adapter.js:98:33)\n    at default (/tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js_next-edge-bootstrap_896e0c.ts._.js:18:278)\n    at /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/node_modules/.pnpm/file+..+next-repo-cc68aa895ffa81a871739457a575a08d_s35yvm4iil2ppnxycg6o257o2y/node_modules/next/dist/server/web/sandbox/sandbox.js:73:30\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async runEdgeFunction (/tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:114:20)\n    at async /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:84:5\n    at async endOperation (/tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:109:13)\n    at async Promise.all (index 0)\n    at async /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:58:13\nevent - updated in 256ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:40:7)"
                ],
                "fullName": "fetch failures have good stack traces in edge runtime when returning `fetch` using an unknown domain, stack traces are preserved",
                "location": null,
                "status": "failed",
                "title": "when returning `fetch` using an unknown domain, stack traces are preserved"
              }
            ],
            "endTime": 1675848727282,
            "message": "  ● fetch failures have good stack traces in edge runtime › when awaiting `fetch` using an unknown domain, stack traces are preserved\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"src/fetcher.js\"\n    Received string:    \"yarn run v1.22.19\n    $ /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/node_modules/.bin/next --turbo\n    >>> TURBOPACK (alpha)·\n    Thank you for trying Next.js v13 with Turbopack! As a reminder,\n    Turbopack is currently in alpha and not yet ready for production.\n    We appreciate your ongoing support as we work to make it ready\n    for everyone.·\n    Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\n    Please direct feedback to: https://nextjs.link/turbopack-feedback·\n    info  - Using locally built binary of @next/swc\n    Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191 --is-next-dev-command --root /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191 --no-open]\n    \u001b[32mready\u001b[39m - started server on 0.0.0.0:32881, url: http://localhost:32881\n    \u001b[35mevent\u001b[39m - initial compilation 6.044ms\n    [500] /api/unknown-domain (1122ms)\n    \"\n\n      23 |         expect(next.cliOutput).toMatch(/at.+\\/pages\\/api\\/unknown-domain.js/)\n      24 |       } else if (isNextDev) {\n    > 25 |         expect(next.cliOutput).toContain('src/fetcher.js')\n         |                                ^\n      26 |\n      27 |         expect(await hasRedbox(browser, true)).toBe(true)\n      28 |         const source = await getRedboxSource(browser)\n\n      at Object.<anonymous> (e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:25:32)\n\n  ● fetch failures have good stack traces in edge runtime › when returning `fetch` using an unknown domain, stack traces are preserved\n\n    TIMED OUT: /at.+\\/pages\\/api\\/unknown-domain-no-await.js/\n\n    yarn run v1.22.19\n    $ /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/node_modules/.bin/next --turbo\n    >>> TURBOPACK (alpha)\n\n    Thank you for trying Next.js v13 with Turbopack! As a reminder,\n    Turbopack is currently in alpha and not yet ready for production.\n    We appreciate your ongoing support as we work to make it ready\n    for everyone.\n\n    Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\n    Please direct feedback to: https://nextjs.link/turbopack-feedback\n\n    info  - Using locally built binary of @next/swc\n    Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191 --is-next-dev-command --root /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191 --no-open]\n    ready - started server on 0.0.0.0:32881, url: http://localhost:32881\n    event - initial compilation 6.044ms\n    [500] /api/unknown-domain (1122ms)\n    event - updated in 1122ms\n    stack is: Error: fetch failed\n\n      at context.fetch (../../tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/node_modules/.pnpm/file+..+next-repo-cc68aa895ffa81a871739457a575a08d_s35yvm4iil2ppnxycg6o257o2y/node_modules/next/dist/server/web/sandbox/context.js:167:38)\n      at Object.UnknownDomainEndpoint [as handler] (../../tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js:13:5)\n      at Object.adapter (../../tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/edge/chunks/b5a0f_next_dist_server_web_adapter.js:98:33)\n      at default (../../tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js_next-edge-bootstrap_896e0c.ts._.js:18:278)\n      at ../../tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/node_modules/.pnpm/file+..+next-repo-cc68aa895ffa81a871739457a575a08d_s35yvm4iil2ppnxycg6o257o2y/node_modules/next/dist/server/web/sandbox/sandbox.js:73:30\n      at async runEdgeFunction (../../tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:114:20)\n      at ../async /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:84:5\n      at async endOperation (../../tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:109:13)\n          at async Promise.all (index 0)\n      at ../async /tmp/next-install-da8d1570df43761cd000789ffc7be3ae53a01def46c1198a16294e6a61cd0191/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:58:13\n      event - updated in 256ms\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:40:7)\n",
            "name": "/work/test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts",
            "startTime": 1675848678176,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (18, 1)",
      "name": "test/integration/edge-runtime-response-error/test/index.test.js",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 2,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 4,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675848819094,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"Expected an instance of Response to be returned\"\nReceived string:    \"Loading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 34251 --root /work --no-open]\n\"\n    at Object.<anonymous> (/work/test/integration/edge-runtime-response-error/test/index.test.js:70:35)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
                ],
                "fullName": "Edge runtime code with imports test error if response is not Response type Edge API dev test Response",
                "location": null,
                "status": "failed",
                "title": "Edge API dev test Response"
              },
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [],
                "fullName": "Edge runtime code with imports test error if response is not Response type Edge API build test Response",
                "location": null,
                "status": "passed",
                "title": "Edge API build test Response"
              },
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"Expected an instance of Response to be returned\"\nReceived string:    \"Loading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 45921 --root /work --no-open]\n\"\n    at Object.<anonymous> (/work/test/integration/edge-runtime-response-error/test/index.test.js:70:35)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
                ],
                "fullName": "Edge runtime code with imports test error if response is not Response type Middleware dev test Response",
                "location": null,
                "status": "failed",
                "title": "Middleware dev test Response"
              },
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [],
                "fullName": "Edge runtime code with imports test error if response is not Response type Middleware build test Response",
                "location": null,
                "status": "passed",
                "title": "Middleware build test Response"
              }
            ],
            "endTime": 1675848862743,
            "message": "  ● Edge runtime code with imports › test error if response is not Response type › Edge API dev test Response\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"Expected an instance of Response to be returned\"\n    Received string:    \"Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 34251 --root /work --no-open]\n    \"\n\n      68 |       context.app = await launchApp(context.appDir, context.appPort, appOption)\n      69 |       const res = await fetchViaHTTP(context.appPort, url)\n    > 70 |       expect(context.logs.stderr).toContain(\n         |                                   ^\n      71 |         'Expected an instance of Response to be returned'\n      72 |       )\n      73 |       expect(res.status).toBe(500)\n\n      at Object.<anonymous> (integration/edge-runtime-response-error/test/index.test.js:70:35)\n\n  ● Edge runtime code with imports › test error if response is not Response type › Middleware dev test Response\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"Expected an instance of Response to be returned\"\n    Received string:    \"Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 45921 --root /work --no-open]\n    \"\n\n      68 |       context.app = await launchApp(context.appDir, context.appPort, appOption)\n      69 |       const res = await fetchViaHTTP(context.appPort, url)\n    > 70 |       expect(context.logs.stderr).toContain(\n         |                                   ^\n      71 |         'Expected an instance of Response to be returned'\n      72 |       )\n      73 |       expect(res.status).toBe(500)\n\n      at Object.<anonymous> (integration/edge-runtime-response-error/test/index.test.js:70:35)\n",
            "name": "/work/test/integration/edge-runtime-response-error/test/index.test.js",
            "startTime": 1675848819188,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (18, 2)",
      "name": "test/development/acceptance-app/editor-links.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 3,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 3,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675848381224,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "api-route-errors cli output"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /pages\\/api/\n\n[500] /api/error (965ms)\n\u001b[2K\u001b[35mevent\u001b[39m - updated in 965ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/development/api-route-errors/index.test.ts:23:5)"
                ],
                "fullName": "api-route-errors cli output error",
                "location": null,
                "status": "failed",
                "title": "error"
              },
              {
                "ancestorTitles": [
                  "api-route-errors cli output"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /pages\\/api/\n\n[500] /api/uncaught-exception (111ms)\n\u001b[2K\u001b[35mevent\u001b[39m - updated in 111ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/development/api-route-errors/index.test.ts:37:5)"
                ],
                "fullName": "api-route-errors cli output uncaught exception",
                "location": null,
                "status": "failed",
                "title": "uncaught exception"
              },
              {
                "ancestorTitles": [
                  "api-route-errors cli output"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /pages\\/api/\n\n[500] /api/unhandled-rejection (144ms)\n\u001b[2K\u001b[35mevent\u001b[39m - updated in 144ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/development/api-route-errors/index.test.ts:55:5)"
                ],
                "fullName": "api-route-errors cli output unhandled rejection",
                "location": null,
                "status": "failed",
                "title": "unhandled rejection"
              }
            ],
            "endTime": 1675848491820,
            "message": "  ● api-route-errors cli output › error\n\n    TIMED OUT: /pages\\/api/\n\n    [500] /api/error (965ms)\n    \u001b[2K\u001b[35mevent\u001b[39m - updated in 965ms\n\n      559 |\n      560 |   if (hardError) {\n    > 561 |     throw new Error('TIMED OUT: ' + regex + '\\n\\n' + content)\n          |           ^\n      562 |   }\n      563 |   return false\n      564 | }\n\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (development/api-route-errors/index.test.ts:23:5)\n\n  ● api-route-errors cli output › uncaught exception\n\n    TIMED OUT: /pages\\/api/\n\n    [500] /api/uncaught-exception (111ms)\n    \u001b[2K\u001b[35mevent\u001b[39m - updated in 111ms\n\n      559 |\n      560 |   if (hardError) {\n    > 561 |     throw new Error('TIMED OUT: ' + regex + '\\n\\n' + content)\n          |           ^\n      562 |   }\n      563 |   return false\n      564 | }\n\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (development/api-route-errors/index.test.ts:37:5)\n\n  ● api-route-errors cli output › unhandled rejection\n\n    TIMED OUT: /pages\\/api/\n\n    [500] /api/unhandled-rejection (144ms)\n    \u001b[2K\u001b[35mevent\u001b[39m - updated in 144ms\n\n      559 |\n      560 |   if (hardError) {\n    > 561 |     throw new Error('TIMED OUT: ' + regex + '\\n\\n' + content)\n          |           ^\n      562 |   }\n      563 |   return false\n      564 | }\n\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (development/api-route-errors/index.test.ts:55:5)\n",
            "name": "/work/test/development/api-route-errors/index.test.ts",
            "startTime": 1675848381318,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (18, 2)",
      "name": "test/e2e/app-dir/app-rendering/rendering.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 2,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675848602416,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "app-dir alias handling"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"click</button>\"\nReceived string:    \"Execution of get_from_source failed·\nCaused by:\n    0: Execution of resolve_source_request failed\n    1: Execution of CombinedContentSource::get failed\n    2: Execution of create_app_source failed\n    3: Execution of load_next_config failed\n    4: Execution of evaluate failed\n    5: node process exited before we could connect to it with exit status: 1\"\n    at Object.<anonymous> (/work/test/e2e/app-dir/app-alias/app-alias.test.ts:16:20)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
                ],
                "fullName": "app-dir alias handling should handle typescript paths alias correctly",
                "location": null,
                "status": "failed",
                "title": "should handle typescript paths alias correctly"
              },
              {
                "ancestorTitles": [
                  "app-dir alias handling"
                ],
                "failureMessages": [
                  "page.waitForSelector: Timeout 30000ms exceeded.\n=========================== logs ===========================\nwaiting for locator('button')\n============================================================\n    at /work/test/lib/browsers/playwright.ts:331:10"
                ],
                "fullName": "app-dir alias handling should resolve css imports from outside with src folder presented",
                "location": null,
                "status": "failed",
                "title": "should resolve css imports from outside with src folder presented"
              }
            ],
            "endTime": 1675848655152,
            "message": "  ● app-dir alias handling › should handle typescript paths alias correctly\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"click</button>\"\n    Received string:    \"Execution of get_from_source failed·\n    Caused by:\n        0: Execution of resolve_source_request failed\n        1: Execution of CombinedContentSource::get failed\n        2: Execution of create_app_source failed\n        3: Execution of load_next_config failed\n        4: Execution of evaluate failed\n        5: node process exited before we could connect to it with exit status: 1\"\n\n      14 |     it('should handle typescript paths alias correctly', async () => {\n      15 |       const html = await next.render('/button')\n    > 16 |       expect(html).toContain('click</button>')\n         |                    ^\n      17 |     })\n      18 |\n      19 |     it('should resolve css imports from outside with src folder presented', async () => {\n\n      at Object.<anonymous> (e2e/app-dir/app-alias/app-alias.test.ts:16:20)\n\n  ● app-dir alias handling › should resolve css imports from outside with src folder presented\n\n    page.waitForSelector: Timeout 30000ms exceeded.\n    =========================== logs ===========================\n    waiting for locator('button')\n    ============================================================\n\n      329 |     return this.chain(() => {\n      330 |       return page\n    > 331 |         .waitForSelector(selector, { timeout, state: 'attached' })\n          |          ^\n      332 |         .then(async (el) => {\n      333 |           // it seems selenium waits longer and tests rely on this behavior\n      334 |           // so we wait for the load event fire before returning\n\n      at lib/browsers/playwright.ts:331:10\n",
            "name": "/work/test/e2e/app-dir/app-alias/app-alias.test.ts",
            "startTime": 1675848602506,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    }
  ]
}