{
  "ref": "de8a3f2c36de1ea2166380da3972c3e3f53a32d0",
  "nextjsVersion": "Next.js v13.1.7-canary.7",
  "result": [
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (16, 1)",
      "name": "test/development/acceptance-app/component-stack.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 1,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 1,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675839435344,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "Component Stack in error overlay"
                ],
                "failureMessages": [
                  "page.waitForSelector: Timeout 30000ms exceeded.\n=========================== logs ===========================\nwaiting for locator('[data-nextjs-toast]')\n============================================================\n    at /work/test/lib/browsers/playwright.ts:331:10"
                ],
                "fullName": "Component Stack in error overlay should show a component stack on hydration error",
                "location": null,
                "status": "failed",
                "title": "should show a component stack on hydration error"
              }
            ],
            "endTime": 1675839498795,
            "message": "  ● Component Stack in error overlay › should show a component stack on hydration error\n\n    page.waitForSelector: Timeout 30000ms exceeded.\n    =========================== logs ===========================\n    waiting for locator('[data-nextjs-toast]')\n    ============================================================\n\n      329 |     return this.chain(() => {\n      330 |       return page\n    > 331 |         .waitForSelector(selector, { timeout, state: 'attached' })\n          |          ^\n      332 |         .then(async (el) => {\n      333 |           // it seems selenium waits longer and tests rely on this behavior\n      334 |           // so we wait for the load event fire before returning\n\n      at lib/browsers/playwright.ts:331:10\n",
            "name": "/work/test/development/acceptance-app/component-stack.test.ts",
            "startTime": 1675839435442,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (16, 1)",
      "name": "test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 2,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675839576045,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "fetch failures have good stack traces in edge runtime"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"src/fetcher.js\"\nReceived string:    \"yarn run v1.22.19\n$ /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/node_modules/.bin/next --turbo\n>>> TURBOPACK (alpha)·\nThank you for trying Next.js v13 with Turbopack! As a reminder,\nTurbopack is currently in alpha and not yet ready for production.\nWe appreciate your ongoing support as we work to make it ready\nfor everyone.·\nLearn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\nPlease direct feedback to: https://nextjs.link/turbopack-feedback·\ninfo  - Using locally built binary of @next/swc\nLoading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f --is-next-dev-command --root /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f --no-open]\n\u001b[32mready\u001b[39m - started server on 0.0.0.0:42849, url: http://localhost:42849\n\u001b[35mevent\u001b[39m - initial compilation 10.187ms\n[500] /api/unknown-domain (1125ms)\n\"\n    at Object.<anonymous> (/work/test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:25:32)"
                ],
                "fullName": "fetch failures have good stack traces in edge runtime when awaiting `fetch` using an unknown domain, stack traces are preserved",
                "location": null,
                "status": "failed",
                "title": "when awaiting `fetch` using an unknown domain, stack traces are preserved"
              },
              {
                "ancestorTitles": [
                  "fetch failures have good stack traces in edge runtime"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /at.+\\/pages\\/api\\/unknown-domain-no-await.js/\n\nyarn run v1.22.19\n$ /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/node_modules/.bin/next --turbo\n>>> TURBOPACK (alpha)\n\nThank you for trying Next.js v13 with Turbopack! As a reminder,\nTurbopack is currently in alpha and not yet ready for production.\nWe appreciate your ongoing support as we work to make it ready\nfor everyone.\n\nLearn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\nPlease direct feedback to: https://nextjs.link/turbopack-feedback\n\ninfo  - Using locally built binary of @next/swc\nLoading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f --is-next-dev-command --root /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f --no-open]\nready - started server on 0.0.0.0:42849, url: http://localhost:42849\nevent - initial compilation 10.187ms\n[500] /api/unknown-domain (1125ms)\nevent - updated in 1125ms\nstack is: Error: fetch failed\n    at context.fetch (/tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/node_modules/.pnpm/file+..+next-repo-a860cfac08881cd4315a097cc82534e0_xsjc4rbmkd2xyjsdoc4tk66gbe/node_modules/next/dist/server/web/sandbox/context.js:167:38)\n    at Object.UnknownDomainEndpoint [as handler] (/tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js:13:5)\n    at Object.adapter (/tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/edge/chunks/a3905_next_dist_server_web_adapter.js:98:33)\n    at default (/tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js_next-edge-bootstrap_d8e977.ts._.js:18:278)\n    at /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/node_modules/.pnpm/file+..+next-repo-a860cfac08881cd4315a097cc82534e0_xsjc4rbmkd2xyjsdoc4tk66gbe/node_modules/next/dist/server/web/sandbox/sandbox.js:73:30\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async runEdgeFunction (/tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:114:20)\n    at async /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:84:5\n    at async endOperation (/tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:109:13)\n    at async Promise.all (index 0)\n    at async /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:58:13\nevent - updated in 268ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:40:7)"
                ],
                "fullName": "fetch failures have good stack traces in edge runtime when returning `fetch` using an unknown domain, stack traces are preserved",
                "location": null,
                "status": "failed",
                "title": "when returning `fetch` using an unknown domain, stack traces are preserved"
              }
            ],
            "endTime": 1675839626328,
            "message": "  ● fetch failures have good stack traces in edge runtime › when awaiting `fetch` using an unknown domain, stack traces are preserved\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"src/fetcher.js\"\n    Received string:    \"yarn run v1.22.19\n    $ /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/node_modules/.bin/next --turbo\n    >>> TURBOPACK (alpha)·\n    Thank you for trying Next.js v13 with Turbopack! As a reminder,\n    Turbopack is currently in alpha and not yet ready for production.\n    We appreciate your ongoing support as we work to make it ready\n    for everyone.·\n    Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\n    Please direct feedback to: https://nextjs.link/turbopack-feedback·\n    info  - Using locally built binary of @next/swc\n    Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f --is-next-dev-command --root /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f --no-open]\n    \u001b[32mready\u001b[39m - started server on 0.0.0.0:42849, url: http://localhost:42849\n    \u001b[35mevent\u001b[39m - initial compilation 10.187ms\n    [500] /api/unknown-domain (1125ms)\n    \"\n\n      23 |         expect(next.cliOutput).toMatch(/at.+\\/pages\\/api\\/unknown-domain.js/)\n      24 |       } else if (isNextDev) {\n    > 25 |         expect(next.cliOutput).toContain('src/fetcher.js')\n         |                                ^\n      26 |\n      27 |         expect(await hasRedbox(browser, true)).toBe(true)\n      28 |         const source = await getRedboxSource(browser)\n\n      at Object.<anonymous> (e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:25:32)\n\n  ● fetch failures have good stack traces in edge runtime › when returning `fetch` using an unknown domain, stack traces are preserved\n\n    TIMED OUT: /at.+\\/pages\\/api\\/unknown-domain-no-await.js/\n\n    yarn run v1.22.19\n    $ /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/node_modules/.bin/next --turbo\n    >>> TURBOPACK (alpha)\n\n    Thank you for trying Next.js v13 with Turbopack! As a reminder,\n    Turbopack is currently in alpha and not yet ready for production.\n    We appreciate your ongoing support as we work to make it ready\n    for everyone.\n\n    Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\n    Please direct feedback to: https://nextjs.link/turbopack-feedback\n\n    info  - Using locally built binary of @next/swc\n    Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f --is-next-dev-command --root /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f --no-open]\n    ready - started server on 0.0.0.0:42849, url: http://localhost:42849\n    event - initial compilation 10.187ms\n    [500] /api/unknown-domain (1125ms)\n    event - updated in 1125ms\n    stack is: Error: fetch failed\n\n      at context.fetch (../../tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/node_modules/.pnpm/file+..+next-repo-a860cfac08881cd4315a097cc82534e0_xsjc4rbmkd2xyjsdoc4tk66gbe/node_modules/next/dist/server/web/sandbox/context.js:167:38)\n      at Object.UnknownDomainEndpoint [as handler] (../../tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js:13:5)\n      at Object.adapter (../../tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/edge/chunks/a3905_next_dist_server_web_adapter.js:98:33)\n      at default (../../tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js_next-edge-bootstrap_d8e977.ts._.js:18:278)\n      at ../../tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/node_modules/.pnpm/file+..+next-repo-a860cfac08881cd4315a097cc82534e0_xsjc4rbmkd2xyjsdoc4tk66gbe/node_modules/next/dist/server/web/sandbox/sandbox.js:73:30\n      at async runEdgeFunction (../../tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:114:20)\n      at ../async /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:84:5\n      at async endOperation (../../tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:109:13)\n          at async Promise.all (index 0)\n      at ../async /tmp/next-install-5e3b9088788f2dec4a1de09311fd90cd7acf6ba61fb5552a4a2d32646520729f/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:58:13\n      event - updated in 268ms\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:40:7)\n",
            "name": "/work/test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts",
            "startTime": 1675839576139,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (16, 1)",
      "name": "test/integration/edge-runtime-response-error/test/index.test.js",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 2,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 4,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675839718361,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"Expected an instance of Response to be returned\"\nReceived string:    \"Loading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 42045 --root /work --no-open]\n\"\n    at Object.<anonymous> (/work/test/integration/edge-runtime-response-error/test/index.test.js:70:35)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
                ],
                "fullName": "Edge runtime code with imports test error if response is not Response type Edge API dev test Response",
                "location": null,
                "status": "failed",
                "title": "Edge API dev test Response"
              },
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [],
                "fullName": "Edge runtime code with imports test error if response is not Response type Edge API build test Response",
                "location": null,
                "status": "passed",
                "title": "Edge API build test Response"
              },
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"Expected an instance of Response to be returned\"\nReceived string:    \"Loading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 33985 --root /work --no-open]\n\"\n    at Object.<anonymous> (/work/test/integration/edge-runtime-response-error/test/index.test.js:70:35)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
                ],
                "fullName": "Edge runtime code with imports test error if response is not Response type Middleware dev test Response",
                "location": null,
                "status": "failed",
                "title": "Middleware dev test Response"
              },
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [],
                "fullName": "Edge runtime code with imports test error if response is not Response type Middleware build test Response",
                "location": null,
                "status": "passed",
                "title": "Middleware build test Response"
              }
            ],
            "endTime": 1675839761331,
            "message": "  ● Edge runtime code with imports › test error if response is not Response type › Edge API dev test Response\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"Expected an instance of Response to be returned\"\n    Received string:    \"Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 42045 --root /work --no-open]\n    \"\n\n      68 |       context.app = await launchApp(context.appDir, context.appPort, appOption)\n      69 |       const res = await fetchViaHTTP(context.appPort, url)\n    > 70 |       expect(context.logs.stderr).toContain(\n         |                                   ^\n      71 |         'Expected an instance of Response to be returned'\n      72 |       )\n      73 |       expect(res.status).toBe(500)\n\n      at Object.<anonymous> (integration/edge-runtime-response-error/test/index.test.js:70:35)\n\n  ● Edge runtime code with imports › test error if response is not Response type › Middleware dev test Response\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"Expected an instance of Response to be returned\"\n    Received string:    \"Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 33985 --root /work --no-open]\n    \"\n\n      68 |       context.app = await launchApp(context.appDir, context.appPort, appOption)\n      69 |       const res = await fetchViaHTTP(context.appPort, url)\n    > 70 |       expect(context.logs.stderr).toContain(\n         |                                   ^\n      71 |         'Expected an instance of Response to be returned'\n      72 |       )\n      73 |       expect(res.status).toBe(500)\n\n      at Object.<anonymous> (integration/edge-runtime-response-error/test/index.test.js:70:35)\n",
            "name": "/work/test/integration/edge-runtime-response-error/test/index.test.js",
            "startTime": 1675839718454,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (16, 2)",
      "name": "test/development/acceptance-app/editor-links.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 3,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 3,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675839659230,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "api-route-errors cli output"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /pages\\/api/\n\n[500] /api/error (935ms)\n\u001b[2K\u001b[35mevent\u001b[39m - updated in 935ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/development/api-route-errors/index.test.ts:23:5)"
                ],
                "fullName": "api-route-errors cli output error",
                "location": null,
                "status": "failed",
                "title": "error"
              },
              {
                "ancestorTitles": [
                  "api-route-errors cli output"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /pages\\/api/\n\n[500] /api/uncaught-exception (106ms)\n\u001b[2K\u001b[35mevent\u001b[39m - updated in 106ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/development/api-route-errors/index.test.ts:37:5)"
                ],
                "fullName": "api-route-errors cli output uncaught exception",
                "location": null,
                "status": "failed",
                "title": "uncaught exception"
              },
              {
                "ancestorTitles": [
                  "api-route-errors cli output"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /pages\\/api/\n\n[500] /api/unhandled-rejection (145ms)\n\u001b[2K\u001b[35mevent\u001b[39m - updated in 145ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/development/api-route-errors/index.test.ts:55:5)"
                ],
                "fullName": "api-route-errors cli output unhandled rejection",
                "location": null,
                "status": "failed",
                "title": "unhandled rejection"
              }
            ],
            "endTime": 1675839769719,
            "message": "  ● api-route-errors cli output › error\n\n    TIMED OUT: /pages\\/api/\n\n    [500] /api/error (935ms)\n    \u001b[2K\u001b[35mevent\u001b[39m - updated in 935ms\n\n      559 |\n      560 |   if (hardError) {\n    > 561 |     throw new Error('TIMED OUT: ' + regex + '\\n\\n' + content)\n          |           ^\n      562 |   }\n      563 |   return false\n      564 | }\n\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (development/api-route-errors/index.test.ts:23:5)\n\n  ● api-route-errors cli output › uncaught exception\n\n    TIMED OUT: /pages\\/api/\n\n    [500] /api/uncaught-exception (106ms)\n    \u001b[2K\u001b[35mevent\u001b[39m - updated in 106ms\n\n      559 |\n      560 |   if (hardError) {\n    > 561 |     throw new Error('TIMED OUT: ' + regex + '\\n\\n' + content)\n          |           ^\n      562 |   }\n      563 |   return false\n      564 | }\n\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (development/api-route-errors/index.test.ts:37:5)\n\n  ● api-route-errors cli output › unhandled rejection\n\n    TIMED OUT: /pages\\/api/\n\n    [500] /api/unhandled-rejection (145ms)\n    \u001b[2K\u001b[35mevent\u001b[39m - updated in 145ms\n\n      559 |\n      560 |   if (hardError) {\n    > 561 |     throw new Error('TIMED OUT: ' + regex + '\\n\\n' + content)\n          |           ^\n      562 |   }\n      563 |   return false\n      564 | }\n\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (development/api-route-errors/index.test.ts:55:5)\n",
            "name": "/work/test/development/api-route-errors/index.test.ts",
            "startTime": 1675839659326,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (16, 2)",
      "name": "test/e2e/app-dir/app-rendering/rendering.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 2,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675839882482,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "app-dir alias handling"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"click</button>\"\nReceived string:    \"Execution of get_from_source failed·\nCaused by:\n    0: Execution of resolve_source_request failed\n    1: Execution of CombinedContentSource::get failed\n    2: Execution of create_app_source failed\n    3: Execution of load_next_config failed\n    4: Execution of evaluate failed\n    5: node process exited before we could connect to it with exit status: 1\"\n    at Object.<anonymous> (/work/test/e2e/app-dir/app-alias/app-alias.test.ts:16:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
                ],
                "fullName": "app-dir alias handling should handle typescript paths alias correctly",
                "location": null,
                "status": "failed",
                "title": "should handle typescript paths alias correctly"
              },
              {
                "ancestorTitles": [
                  "app-dir alias handling"
                ],
                "failureMessages": [
                  "page.waitForSelector: Timeout 30000ms exceeded.\n=========================== logs ===========================\nwaiting for locator('button')\n============================================================\n    at /work/test/lib/browsers/playwright.ts:331:10"
                ],
                "fullName": "app-dir alias handling should resolve css imports from outside with src folder presented",
                "location": null,
                "status": "failed",
                "title": "should resolve css imports from outside with src folder presented"
              }
            ],
            "endTime": 1675839935155,
            "message": "  ● app-dir alias handling › should handle typescript paths alias correctly\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"click</button>\"\n    Received string:    \"Execution of get_from_source failed·\n    Caused by:\n        0: Execution of resolve_source_request failed\n        1: Execution of CombinedContentSource::get failed\n        2: Execution of create_app_source failed\n        3: Execution of load_next_config failed\n        4: Execution of evaluate failed\n        5: node process exited before we could connect to it with exit status: 1\"\n\n      14 |     it('should handle typescript paths alias correctly', async () => {\n      15 |       const html = await next.render('/button')\n    > 16 |       expect(html).toContain('click</button>')\n         |                    ^\n      17 |     })\n      18 |\n      19 |     it('should resolve css imports from outside with src folder presented', async () => {\n\n      at Object.<anonymous> (e2e/app-dir/app-alias/app-alias.test.ts:16:20)\n\n  ● app-dir alias handling › should resolve css imports from outside with src folder presented\n\n    page.waitForSelector: Timeout 30000ms exceeded.\n    =========================== logs ===========================\n    waiting for locator('button')\n    ============================================================\n\n      329 |     return this.chain(() => {\n      330 |       return page\n    > 331 |         .waitForSelector(selector, { timeout, state: 'attached' })\n          |          ^\n      332 |         .then(async (el) => {\n      333 |           // it seems selenium waits longer and tests rely on this behavior\n      334 |           // so we wait for the load event fire before returning\n\n      at lib/browsers/playwright.ts:331:10\n",
            "name": "/work/test/e2e/app-dir/app-alias/app-alias.test.ts",
            "startTime": 1675839882571,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (16, 2)",
      "name": "test/integration/next-image-legacy/asset-prefix/test/index.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 1,
        "numPassedTestSuites": 0,
        "numPassedTests": 1,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 2,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675840130529,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "Image Component assetPrefix Tests",
                  "dev mode"
                ],
                "failureMessages": [
                  "Error: expect(received).toMatch(expected)\n\nMatcher error: received value must be a string\n\nReceived has value: null\n    at Object.<anonymous> (/work/test/integration/next-image-legacy/asset-prefix/test/index.test.ts:34:25)"
                ],
                "fullName": "Image Component assetPrefix Tests dev mode should include assetPrefix when placeholder=blur during next dev",
                "location": null,
                "status": "failed",
                "title": "should include assetPrefix when placeholder=blur during next dev"
              },
              {
                "ancestorTitles": [
                  "Image Component assetPrefix Tests",
                  "server mode"
                ],
                "failureMessages": [],
                "fullName": "Image Component assetPrefix Tests server mode should use base64 data url with placeholder=blur during next start",
                "location": null,
                "status": "passed",
                "title": "should use base64 data url with placeholder=blur during next start"
              }
            ],
            "endTime": 1675840161580,
            "message": "  ● Image Component assetPrefix Tests › dev mode › should include assetPrefix when placeholder=blur during next dev\n\n    expect(received).toMatch(expected)\n\n    Matcher error: received value must be a string\n\n    Received has value: null\n\n      32 |           `document.getElementById('${id}').style['background-image']`\n      33 |         )\n    > 34 |         expect(bgImage).toMatch(\n         |                         ^\n      35 |           /\\/_next\\/image\\?url=https%3A%2F%2Fexample.com%2Fpre%2F_next%2Fstatic%2Fmedia%2Ftest(.+).jpg&w=8&q=70/\n      36 |         )\n      37 |       } finally {\n\n      at Object.<anonymous> (integration/next-image-legacy/asset-prefix/test/index.test.ts:34:25)\n",
            "name": "/work/test/integration/next-image-legacy/asset-prefix/test/index.test.ts",
            "startTime": 1675840130621,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (18, 1)",
      "name": "test/development/acceptance-app/component-stack.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 1,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 1,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675839605859,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "Component Stack in error overlay"
                ],
                "failureMessages": [
                  "page.waitForSelector: Timeout 30000ms exceeded.\n=========================== logs ===========================\nwaiting for locator('[data-nextjs-toast]')\n============================================================\n    at /work/test/lib/browsers/playwright.ts:331:10"
                ],
                "fullName": "Component Stack in error overlay should show a component stack on hydration error",
                "location": null,
                "status": "failed",
                "title": "should show a component stack on hydration error"
              }
            ],
            "endTime": 1675839669481,
            "message": "  ● Component Stack in error overlay › should show a component stack on hydration error\n\n    page.waitForSelector: Timeout 30000ms exceeded.\n    =========================== logs ===========================\n    waiting for locator('[data-nextjs-toast]')\n    ============================================================\n\n      329 |     return this.chain(() => {\n      330 |       return page\n    > 331 |         .waitForSelector(selector, { timeout, state: 'attached' })\n          |          ^\n      332 |         .then(async (el) => {\n      333 |           // it seems selenium waits longer and tests rely on this behavior\n      334 |           // so we wait for the load event fire before returning\n\n      at lib/browsers/playwright.ts:331:10\n",
            "name": "/work/test/development/acceptance-app/component-stack.test.ts",
            "startTime": 1675839605955,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (18, 1)",
      "name": "test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 2,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675839747382,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "fetch failures have good stack traces in edge runtime"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"src/fetcher.js\"\nReceived string:    \"yarn run v1.22.19\n$ /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/node_modules/.bin/next --turbo\n>>> TURBOPACK (alpha)·\nThank you for trying Next.js v13 with Turbopack! As a reminder,\nTurbopack is currently in alpha and not yet ready for production.\nWe appreciate your ongoing support as we work to make it ready\nfor everyone.·\nLearn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\nPlease direct feedback to: https://nextjs.link/turbopack-feedback·\ninfo  - Using locally built binary of @next/swc\nLoading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523 --is-next-dev-command --root /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523 --no-open]\n\u001b[32mready\u001b[39m - started server on 0.0.0.0:37409, url: http://localhost:37409\n\u001b[35mevent\u001b[39m - initial compilation 5.647ms\n[500] /api/unknown-domain (1202ms)\n\"\n    at Object.<anonymous> (/work/test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:25:32)"
                ],
                "fullName": "fetch failures have good stack traces in edge runtime when awaiting `fetch` using an unknown domain, stack traces are preserved",
                "location": null,
                "status": "failed",
                "title": "when awaiting `fetch` using an unknown domain, stack traces are preserved"
              },
              {
                "ancestorTitles": [
                  "fetch failures have good stack traces in edge runtime"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /at.+\\/pages\\/api\\/unknown-domain-no-await.js/\n\nyarn run v1.22.19\n$ /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/node_modules/.bin/next --turbo\n>>> TURBOPACK (alpha)\n\nThank you for trying Next.js v13 with Turbopack! As a reminder,\nTurbopack is currently in alpha and not yet ready for production.\nWe appreciate your ongoing support as we work to make it ready\nfor everyone.\n\nLearn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\nPlease direct feedback to: https://nextjs.link/turbopack-feedback\n\ninfo  - Using locally built binary of @next/swc\nLoading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523 --is-next-dev-command --root /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523 --no-open]\nready - started server on 0.0.0.0:37409, url: http://localhost:37409\nevent - initial compilation 5.647ms\n[500] /api/unknown-domain (1202ms)\nevent - updated in 1202ms\nstack is: Error: fetch failed\n    at context.fetch (/tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/node_modules/.pnpm/file+..+next-repo-5b5a937479924a79bdad24d8e0cda180_34vgvqugs2c6fxmlbdpih56wiy/node_modules/next/dist/server/web/sandbox/context.js:167:38)\n    at Object.UnknownDomainEndpoint [as handler] (/tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js:13:5)\n    at Object.adapter (/tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/edge/chunks/b5f89_next_dist_server_web_adapter.js:98:33)\n    at default (/tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js_next-edge-bootstrap_3dc858.ts._.js:18:278)\n    at /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/node_modules/.pnpm/file+..+next-repo-5b5a937479924a79bdad24d8e0cda180_34vgvqugs2c6fxmlbdpih56wiy/node_modules/next/dist/server/web/sandbox/sandbox.js:73:30\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async runEdgeFunction (/tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:114:20)\n    at async /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:84:5\n    at async endOperation (/tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:109:13)\n    at async Promise.all (index 0)\n    at async /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:58:13\nevent - updated in 273ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:40:7)"
                ],
                "fullName": "fetch failures have good stack traces in edge runtime when returning `fetch` using an unknown domain, stack traces are preserved",
                "location": null,
                "status": "failed",
                "title": "when returning `fetch` using an unknown domain, stack traces are preserved"
              }
            ],
            "endTime": 1675839798595,
            "message": "  ● fetch failures have good stack traces in edge runtime › when awaiting `fetch` using an unknown domain, stack traces are preserved\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"src/fetcher.js\"\n    Received string:    \"yarn run v1.22.19\n    $ /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/node_modules/.bin/next --turbo\n    >>> TURBOPACK (alpha)·\n    Thank you for trying Next.js v13 with Turbopack! As a reminder,\n    Turbopack is currently in alpha and not yet ready for production.\n    We appreciate your ongoing support as we work to make it ready\n    for everyone.·\n    Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\n    Please direct feedback to: https://nextjs.link/turbopack-feedback·\n    info  - Using locally built binary of @next/swc\n    Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523 --is-next-dev-command --root /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523 --no-open]\n    \u001b[32mready\u001b[39m - started server on 0.0.0.0:37409, url: http://localhost:37409\n    \u001b[35mevent\u001b[39m - initial compilation 5.647ms\n    [500] /api/unknown-domain (1202ms)\n    \"\n\n      23 |         expect(next.cliOutput).toMatch(/at.+\\/pages\\/api\\/unknown-domain.js/)\n      24 |       } else if (isNextDev) {\n    > 25 |         expect(next.cliOutput).toContain('src/fetcher.js')\n         |                                ^\n      26 |\n      27 |         expect(await hasRedbox(browser, true)).toBe(true)\n      28 |         const source = await getRedboxSource(browser)\n\n      at Object.<anonymous> (e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:25:32)\n\n  ● fetch failures have good stack traces in edge runtime › when returning `fetch` using an unknown domain, stack traces are preserved\n\n    TIMED OUT: /at.+\\/pages\\/api\\/unknown-domain-no-await.js/\n\n    yarn run v1.22.19\n    $ /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/node_modules/.bin/next --turbo\n    >>> TURBOPACK (alpha)\n\n    Thank you for trying Next.js v13 with Turbopack! As a reminder,\n    Turbopack is currently in alpha and not yet ready for production.\n    We appreciate your ongoing support as we work to make it ready\n    for everyone.\n\n    Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack\n    Please direct feedback to: https://nextjs.link/turbopack-feedback\n\n    info  - Using locally built binary of @next/swc\n    Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523 --is-next-dev-command --root /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523 --no-open]\n    ready - started server on 0.0.0.0:37409, url: http://localhost:37409\n    event - initial compilation 5.647ms\n    [500] /api/unknown-domain (1202ms)\n    event - updated in 1202ms\n    stack is: Error: fetch failed\n\n      at context.fetch (../../tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/node_modules/.pnpm/file+..+next-repo-5b5a937479924a79bdad24d8e0cda180_34vgvqugs2c6fxmlbdpih56wiy/node_modules/next/dist/server/web/sandbox/context.js:167:38)\n      at Object.UnknownDomainEndpoint [as handler] (../../tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js:13:5)\n      at Object.adapter (../../tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/edge/chunks/b5f89_next_dist_server_web_adapter.js:98:33)\n      at default (../../tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/edge/chunks/pages_api_unknown-domain-no-await.js_next-edge-bootstrap_3dc858.ts._.js:18:278)\n      at ../../tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/node_modules/.pnpm/file+..+next-repo-5b5a937479924a79bdad24d8e0cda180_34vgvqugs2c6fxmlbdpih56wiy/node_modules/next/dist/server/web/sandbox/sandbox.js:73:30\n      at async runEdgeFunction (../../tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:114:20)\n      at ../async /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/api/unknown-domain-no-await/chunks/_d933a8._.js:84:5\n      at async endOperation (../../tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:109:13)\n          at async Promise.all (index 0)\n      at ../async /tmp/next-install-aa7526a494679bb54bc8b3865f2d933018085e2448ed07d7d7b9535085b41523/.next/server/pages/api/unknown-domain-no-await/chunks/[embedded_modules]_@vercel_turbopack-next_internal_api-server-handler.ts._.js:58:13\n      event - updated in 273ms\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts:40:7)\n",
            "name": "/work/test/e2e/fetch-failures-have-good-stack-traces-in-edge-runtime/fetch-failures-have-good-stack-traces-in-edge-runtime.test.ts",
            "startTime": 1675839747484,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (18, 1)",
      "name": "test/integration/edge-runtime-response-error/test/index.test.js",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 2,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 4,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675839897921,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"Expected an instance of Response to be returned\"\nReceived string:    \"Loading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 46145 --root /work --no-open]\n\"\n    at Object.<anonymous> (/work/test/integration/edge-runtime-response-error/test/index.test.js:70:35)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
                ],
                "fullName": "Edge runtime code with imports test error if response is not Response type Edge API dev test Response",
                "location": null,
                "status": "failed",
                "title": "Edge API dev test Response"
              },
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [],
                "fullName": "Edge runtime code with imports test error if response is not Response type Edge API build test Response",
                "location": null,
                "status": "passed",
                "title": "Edge API build test Response"
              },
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"Expected an instance of Response to be returned\"\nReceived string:    \"Loading custom turbopack binary from /work/next-dev\nRunning turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 32925 --root /work --no-open]\n\"\n    at Object.<anonymous> (/work/test/integration/edge-runtime-response-error/test/index.test.js:70:35)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
                ],
                "fullName": "Edge runtime code with imports test error if response is not Response type Middleware dev test Response",
                "location": null,
                "status": "failed",
                "title": "Middleware dev test Response"
              },
              {
                "ancestorTitles": [
                  "Edge runtime code with imports",
                  "test error if response is not Response type"
                ],
                "failureMessages": [],
                "fullName": "Edge runtime code with imports test error if response is not Response type Middleware build test Response",
                "location": null,
                "status": "passed",
                "title": "Middleware build test Response"
              }
            ],
            "endTime": 1675839942733,
            "message": "  ● Edge runtime code with imports › test error if response is not Response type › Edge API dev test Response\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"Expected an instance of Response to be returned\"\n    Received string:    \"Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 46145 --root /work --no-open]\n    \"\n\n      68 |       context.app = await launchApp(context.appDir, context.appPort, appOption)\n      69 |       const res = await fetchViaHTTP(context.appPort, url)\n    > 70 |       expect(context.logs.stderr).toContain(\n         |                                   ^\n      71 |         'Expected an instance of Response to be returned'\n      72 |       )\n      73 |       expect(res.status).toBe(500)\n\n      at Object.<anonymous> (integration/edge-runtime-response-error/test/index.test.js:70:35)\n\n  ● Edge runtime code with imports › test error if response is not Response type › Middleware dev test Response\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"Expected an instance of Response to be returned\"\n    Received string:    \"Loading custom turbopack binary from /work/next-dev\n    Running turbopack with args: [--dev /work/test/integration/edge-runtime-response-error --is-next-dev-command --port 32925 --root /work --no-open]\n    \"\n\n      68 |       context.app = await launchApp(context.appDir, context.appPort, appOption)\n      69 |       const res = await fetchViaHTTP(context.appPort, url)\n    > 70 |       expect(context.logs.stderr).toContain(\n         |                                   ^\n      71 |         'Expected an instance of Response to be returned'\n      72 |       )\n      73 |       expect(res.status).toBe(500)\n\n      at Object.<anonymous> (integration/edge-runtime-response-error/test/index.test.js:70:35)\n",
            "name": "/work/test/integration/edge-runtime-response-error/test/index.test.js",
            "startTime": 1675839898032,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (18, 2)",
      "name": "test/development/acceptance-app/editor-links.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 3,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 3,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675839658982,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "api-route-errors cli output"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /pages\\/api/\n\n[500] /api/error (947ms)\n\u001b[2K\u001b[35mevent\u001b[39m - updated in 947ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at listOnTimeout (node:internal/timers:538:9)\n    at processTimers (node:internal/timers:512:7)\n    at Object.<anonymous> (/work/test/development/api-route-errors/index.test.ts:23:5)"
                ],
                "fullName": "api-route-errors cli output error",
                "location": null,
                "status": "failed",
                "title": "error"
              },
              {
                "ancestorTitles": [
                  "api-route-errors cli output"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /pages\\/api/\n\n[500] /api/uncaught-exception (108ms)\n\u001b[2K\u001b[35mevent\u001b[39m - updated in 108ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/development/api-route-errors/index.test.ts:37:5)"
                ],
                "fullName": "api-route-errors cli output uncaught exception",
                "location": null,
                "status": "failed",
                "title": "uncaught exception"
              },
              {
                "ancestorTitles": [
                  "api-route-errors cli output"
                ],
                "failureMessages": [
                  "Error: TIMED OUT: /pages\\/api/\n\n[500] /api/unhandled-rejection (147ms)\n\u001b[2K\u001b[35mevent\u001b[39m - updated in 147ms\n\n    at check (/work/test/lib/next-test-utils.js:561:11)\n    at Object.<anonymous> (/work/test/development/api-route-errors/index.test.ts:55:5)"
                ],
                "fullName": "api-route-errors cli output unhandled rejection",
                "location": null,
                "status": "failed",
                "title": "unhandled rejection"
              }
            ],
            "endTime": 1675839769570,
            "message": "  ● api-route-errors cli output › error\n\n    TIMED OUT: /pages\\/api/\n\n    [500] /api/error (947ms)\n    \u001b[2K\u001b[35mevent\u001b[39m - updated in 947ms\n\n      559 |\n      560 |   if (hardError) {\n    > 561 |     throw new Error('TIMED OUT: ' + regex + '\\n\\n' + content)\n          |           ^\n      562 |   }\n      563 |   return false\n      564 | }\n\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (development/api-route-errors/index.test.ts:23:5)\n\n  ● api-route-errors cli output › uncaught exception\n\n    TIMED OUT: /pages\\/api/\n\n    [500] /api/uncaught-exception (108ms)\n    \u001b[2K\u001b[35mevent\u001b[39m - updated in 108ms\n\n      559 |\n      560 |   if (hardError) {\n    > 561 |     throw new Error('TIMED OUT: ' + regex + '\\n\\n' + content)\n          |           ^\n      562 |   }\n      563 |   return false\n      564 | }\n\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (development/api-route-errors/index.test.ts:37:5)\n\n  ● api-route-errors cli output › unhandled rejection\n\n    TIMED OUT: /pages\\/api/\n\n    [500] /api/unhandled-rejection (147ms)\n    \u001b[2K\u001b[35mevent\u001b[39m - updated in 147ms\n\n      559 |\n      560 |   if (hardError) {\n    > 561 |     throw new Error('TIMED OUT: ' + regex + '\\n\\n' + content)\n          |           ^\n      562 |   }\n      563 |   return false\n      564 | }\n\n      at check (lib/next-test-utils.js:561:11)\n      at Object.<anonymous> (development/api-route-errors/index.test.ts:55:5)\n",
            "name": "/work/test/development/api-route-errors/index.test.ts",
            "startTime": 1675839659075,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (18, 2)",
      "name": "test/e2e/app-dir/app-rendering/rendering.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 2,
        "numPassedTestSuites": 0,
        "numPassedTests": 0,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 2,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675839881437,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "app-dir alias handling"
                ],
                "failureMessages": [
                  "Error: expect(received).toContain(expected) // indexOf\n\nExpected substring: \"click</button>\"\nReceived string:    \"Execution of get_from_source failed·\nCaused by:\n    0: Execution of resolve_source_request failed\n    1: Execution of CombinedContentSource::get failed\n    2: Execution of create_app_source failed\n    3: Execution of load_next_config failed\n    4: Execution of evaluate failed\n    5: node process exited before we could connect to it with exit status: 1\"\n    at Object.<anonymous> (/work/test/e2e/app-dir/app-alias/app-alias.test.ts:16:20)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
                ],
                "fullName": "app-dir alias handling should handle typescript paths alias correctly",
                "location": null,
                "status": "failed",
                "title": "should handle typescript paths alias correctly"
              },
              {
                "ancestorTitles": [
                  "app-dir alias handling"
                ],
                "failureMessages": [
                  "page.waitForSelector: Timeout 30000ms exceeded.\n=========================== logs ===========================\nwaiting for locator('button')\n============================================================\n    at /work/test/lib/browsers/playwright.ts:331:10"
                ],
                "fullName": "app-dir alias handling should resolve css imports from outside with src folder presented",
                "location": null,
                "status": "failed",
                "title": "should resolve css imports from outside with src folder presented"
              }
            ],
            "endTime": 1675839934216,
            "message": "  ● app-dir alias handling › should handle typescript paths alias correctly\n\n    expect(received).toContain(expected) // indexOf\n\n    Expected substring: \"click</button>\"\n    Received string:    \"Execution of get_from_source failed·\n    Caused by:\n        0: Execution of resolve_source_request failed\n        1: Execution of CombinedContentSource::get failed\n        2: Execution of create_app_source failed\n        3: Execution of load_next_config failed\n        4: Execution of evaluate failed\n        5: node process exited before we could connect to it with exit status: 1\"\n\n      14 |     it('should handle typescript paths alias correctly', async () => {\n      15 |       const html = await next.render('/button')\n    > 16 |       expect(html).toContain('click</button>')\n         |                    ^\n      17 |     })\n      18 |\n      19 |     it('should resolve css imports from outside with src folder presented', async () => {\n\n      at Object.<anonymous> (e2e/app-dir/app-alias/app-alias.test.ts:16:20)\n\n  ● app-dir alias handling › should resolve css imports from outside with src folder presented\n\n    page.waitForSelector: Timeout 30000ms exceeded.\n    =========================== logs ===========================\n    waiting for locator('button')\n    ============================================================\n\n      329 |     return this.chain(() => {\n      330 |       return page\n    > 331 |         .waitForSelector(selector, { timeout, state: 'attached' })\n          |          ^\n      332 |         .then(async (el) => {\n      333 |           // it seems selenium waits longer and tests rely on this behavior\n      334 |           // so we wait for the load event fire before returning\n\n      at lib/browsers/playwright.ts:331:10\n",
            "name": "/work/test/e2e/app-dir/app-alias/app-alias.test.ts",
            "startTime": 1675839881528,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    },
    {
      "job": "Execute Next.js integration workflow / Next.js integration test (18, 2)",
      "name": "test/integration/next-image-legacy/asset-prefix/test/index.test.ts",
      "data": {
        "numFailedTestSuites": 1,
        "numFailedTests": 1,
        "numPassedTestSuites": 0,
        "numPassedTests": 1,
        "numPendingTestSuites": 0,
        "numPendingTests": 0,
        "numRuntimeErrorTestSuites": 0,
        "numTodoTests": 0,
        "numTotalTestSuites": 1,
        "numTotalTests": 2,
        "openHandles": [],
        "snapshot": {
          "added": 0,
          "didUpdate": false,
          "failure": false,
          "filesAdded": 0,
          "filesRemoved": 0,
          "filesRemovedList": [],
          "filesUnmatched": 0,
          "filesUpdated": 0,
          "matched": 0,
          "total": 0,
          "unchecked": 0,
          "uncheckedKeysByFile": [],
          "unmatched": 0,
          "updated": 0
        },
        "startTime": 1675840129369,
        "success": false,
        "testResults": [
          {
            "assertionResults": [
              {
                "ancestorTitles": [
                  "Image Component assetPrefix Tests",
                  "dev mode"
                ],
                "failureMessages": [
                  "Error: expect(received).toMatch(expected)\n\nMatcher error: received value must be a string\n\nReceived has value: null\n    at Object.<anonymous> (/work/test/integration/next-image-legacy/asset-prefix/test/index.test.ts:34:25)"
                ],
                "fullName": "Image Component assetPrefix Tests dev mode should include assetPrefix when placeholder=blur during next dev",
                "location": null,
                "status": "failed",
                "title": "should include assetPrefix when placeholder=blur during next dev"
              },
              {
                "ancestorTitles": [
                  "Image Component assetPrefix Tests",
                  "server mode"
                ],
                "failureMessages": [],
                "fullName": "Image Component assetPrefix Tests server mode should use base64 data url with placeholder=blur during next start",
                "location": null,
                "status": "passed",
                "title": "should use base64 data url with placeholder=blur during next start"
              }
            ],
            "endTime": 1675840160598,
            "message": "  ● Image Component assetPrefix Tests › dev mode › should include assetPrefix when placeholder=blur during next dev\n\n    expect(received).toMatch(expected)\n\n    Matcher error: received value must be a string\n\n    Received has value: null\n\n      32 |           `document.getElementById('${id}').style['background-image']`\n      33 |         )\n    > 34 |         expect(bgImage).toMatch(\n         |                         ^\n      35 |           /\\/_next\\/image\\?url=https%3A%2F%2Fexample.com%2Fpre%2F_next%2Fstatic%2Fmedia%2Ftest(.+).jpg&w=8&q=70/\n      36 |         )\n      37 |       } finally {\n\n      at Object.<anonymous> (integration/next-image-legacy/asset-prefix/test/index.test.ts:34:25)\n",
            "name": "/work/test/integration/next-image-legacy/asset-prefix/test/index.test.ts",
            "startTime": 1675840129479,
            "status": "failed",
            "summary": ""
          }
        ],
        "wasInterrupted": false
      }
    }
  ]
}